export default {
  home: require("@/assets/icons/home.png"),
  profile: require("@/assets/icons/profile.png"),
  qr: require("@/assets/icons/qr.png"),
  search: require("@/assets/icons/search.png"),
  points: require("@/assets/icons/points.png"),
  flashon: require("@/assets/icons/flashon.png"),
  flashoff: require("@/assets/icons/flashoff.png"),
  cameraIcon: require("@/assets/icons/camera.png"),
  wishlist: require("@/assets/icons/wishlist.png"),
  add: require("@/assets/icons/add.png"),
  remove: require("@/assets/icons/remove.png"),
  cart: require("@/assets/icons/cart.png"),
  wishlistcart: require("@/assets/icons/wishlistcart.png"),
  arrowRight: require("@/assets/icons/arrowRight.png"),
  eye: require("@/assets/icons/eye.png"),
  eyeHide: require("@/assets/icons/eye-hide.png"),
};
